version: '3.8'

services:
  neo-db:
    container_name: neo4j
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/Neo4jSecret
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - ./neo4j_db/data:/data
      - ./neo4j_db/logs:/logs
      - ./neo4j_db/import:/var/lib/neo4j/import
      - ./neo4j_db/plugins:/plugins

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    ports:
      - 6333:6333
    volumes:
      - qdrant_data:/qdrant/storage  

  # app:
  #   build: 
  #     context: ./watchflix
  #     dockerfile: Dockerfile
  #   command: python manage.py runserver 0.0.0.0:8000
  #   restart: always
    
  #   depends_on:
  #     - neo-db
  #     - qdrant
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - NEO4J_URI=neo4j://neo-db:7687
  #     - NEO4J_USER=neo4j
  #     - NEO4J_PASSWORD=Neo4jSecret
  #     - QDRANT_URI=http://qdrant:6333

  # react-app:
  #   build:
  #     context: ./watchflix-frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./watchflix-frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "5173:5173"
  #   command: npm run dev
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   depends_on:
  #     - app

volumes:
  neo4j_data:
  neo4j_logs:
  qdrant_data:
