# Generated by Django 5.1.1 on 2024-09-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchhistory',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
