# Generated by Django 5.1.1 on 2024-09-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_history', '0002_alter_watchhistory_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchhistory',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
