# Generated by Django 5.1.1 on 2024-09-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AddField(
            model_name='director',
            name='movies',
            field=models.ManyToManyField(related_name='directors', to='movies.movie'),
        ),
    ]
