# Generated by Django 5.1.1 on 2024-09-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('movies', '0003_remove_movie_director_director_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='followers',
            field=models.ManyToManyField(related_name='followed_actors', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='director',
            name='followers',
            field=models.ManyToManyField(related_name='followed_directors', to='accounts.userprofile'),
        ),
    ]
